---
title: "Generative Art"
author: "Dylan Li"
format: html
editor: visual
---

## Libraries

```{r}
library(ggplot2)
library(tibble)
library(dplyr)
```

## Second Piece

### Data Generation

```{r}
sample_data <- function(seed = NULL, n = 100, z = 1){
  if(!is.null(seed)) set.seed(seed)
  dat <- tibble(
    x0 = seq(0, -0.00000001 + z, by = 1/(n/z)),
    y0 = seq(z + 0, 0.00000001, by = -1/(n/z)),
    x1 = x0 + runif(n, min = -.2, max = .2),
    y1 = y0 + runif(n, min = -.2, max = .2),
    shade = runif(n), 
    size = runif(n)/n,
    shape = factor(sample(0:22, size = n, replace = TRUE))
  )
}
```

```{r}
polar_styled_plot <- function(data = NULL, palette) {
  ggplot(
    data = data,
    mapping = aes(
      x = x0,
      y = y0,
      xend = x1,
      yend = y1,
      colour = shade,
      size = size
    )) + 
    coord_polar(clip = "off") +
    scale_y_continuous(
      expand = c(0, 0),
      limits = c(0, 1), 
      oob = scales::oob_keep
    ) +
    scale_x_continuous(
      expand = c(0, 0), 
      limits = c(0, 1), 
      oob = scales::oob_keep
    ) + 
    scale_colour_gradientn(colours = palette) + 
    scale_size(range = c(0, 10)) + 
    theme_void() + 
    guides(
      colour = guide_none(),
      size = guide_none(),
      fill = guide_none(),
      shape = guide_none()
    )
}
```

```{r}
sample_canva <- function(seed = NULL) {
  if(!is.null(seed)) set.seed(seed)
  sample(ggthemes::canva_palettes, 1)[[1]]
}
```

```{r}
dat <- sample_data(n = 5000, seed = 1, z = 1) 
pal <- sample_canva(seed = 17)

polar_styled_plot(data = dat, palette = pal) + geom_segment()

```
